artifact_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    non_tumor_source_URL: https://github.com/udita1903/Computer-Vision/raw/main/notumor.zip
    golima_source_URL: https://github.com/udita1903/Computer-Vision/raw/main/glioma.zip

    non_tumor_local_file: artifacts/data_ingestion/non_tumor_data.zip
    golima_local_file: artifacts/data_ingestion/golima.zip
    unzip_dir: artifacts/data_ingestion



prepare_base_model :
    root_dir : artifacts/prepare_base_model
    base_model_path: artifacts/base_model/prepare_base_model.h5
    updated_base_model_path : artifacts/base_model/prepare_base_model_updated.h5